schema_version: 20180708
name: authorizerfnjava
version: 0.0.70
runtime: java
build_image: fnproject/fn-java-fdk-build:jdk17-1.0.207
run_image: fnproject/fn-java-fdk:jre17-1.0.207
cmd: com.example.fn.HelloFunction::handleRequest
triggers:
- name: invoke
  type: http
  source: /handleRequest
